### ISSUE TITLE
Explore optimal `MAX_COVALENT_DISTANCE` in domain/forcefield/__init__.py

### ISSUE THREAD

**Issue by KevinVG207** [DeepRank/deeprank-core#205]
Hi,
Deeprank-core currently uses a `MAX_COVALENT_DISTANCE` of 3.0. But by visually inspecting some tests of the resulting graphs, I noticed that there are a lot of wrongly detected covalent bonds and even covalent bonds between separate chains are formed. See this screenshot of only the covalent bonds:
(Red = peptide, blue = MHC, green = bonds between peptide and MHC chains)
![cutoff_3 0_both](https://user-images.githubusercontent.com/19467234/195114960-e75d2c8e-b19c-4ad2-bf5d-cae193f74c48.png)

Daniel and I determined that 2.1 might be a better cutoff value. This screenshot shows the same protein complex with the 2.1 cutoff value.
![cutoff_2 1_both](https://user-images.githubusercontent.com/19467234/195115615-bdb566f2-35b2-4f61-aedd-e3a104447e51.png)

Do you agree?

@LilySnow @DTRademaker

**Comment by DaniBodor** [comment]
A couple of points here:

- How can you be sure that at cutoff of 2.1 you are not missing any true covalent bonds?
  - Is there any literature on what a good cutoff value should be? Other people must have looked into this before.
 
- Currently, the only information that is used for determining whether two nodes have a covalent edge or not is their distance.
  - Is there any other information in the pdb file or anywhere that can help determining whether there is a covalent bond or not?
  - Given that distance is a feature in itself, what is the point of having an additional feature for covalent bonding (which is 100% correlated to distance)?
    - I guess if for some reason you want to exclude the distance feature, then covalent can be informative. Maybe we should implement something that automatically ignores the covalent feature if distance is used.

**Comment by DTRademaker** [comment]
**"How can you be sure that at cutoff of 2.1 you are not missing any true covalent bonds? Is there any literature on what a good cutoff value should be? Other people must have looked into this before."**
We can't, we just visually saw that anything greater than this number resulted in false covalent bonds, and that all covalent boonds we expected were there. There is indeed literature about bondlengths, each atom-atom combinations has its own ranges for bondlengths. 

**"Currently, the only information that is used for determining whether two nodes have a covalent edge or not is their distance. Is there any other information in the pdb file or anywhere that can help determining whether there is a covalent bond or not?**"
Nope, but atoms normally repel each other so if you find 2 atoms in close vicinity they are either bonded or forced in the same neighborhood by a 3rd atom.

**"If there isn't, then what is the point of having an additional feature for covalent bonding (which is 100% correlated to distance)? Maybe we should implement something that automatically ignores the covalent feature if distance is used (if it is not used for some reason, then covalent can be useful)."**
Because they can be relatively easily predicted and provide a huge source of information to the neural network. I, and others, are convinced covalent bond information is one of those features that should always be used.

**"The feature is still useful for building visualization, so maybe we should make it a metafeature that is not used for training, but only for making visualizations."**
I cannot imagine any scenario where this feature would not be important. Let's keep it as a edge-feature :)

**Comment by gcroci2** [comment]
Nice discussion :) I agree that we should keep this edge-feature. We're going to determine features importance soon, and it will be clear if it's really useful for the network or not. 

Can we verify that 2.1 is a good value for residue level representation as well? I know it should be sort of granted, but I think it'd be better to check anyway. If you share the code you used for representing covalent bonds for atomic level, I could verify it myself @KevinVG207 @DTRademaker. Then we can modify deeprankcore with the new value.

**Comment by DTRademaker** [comment]
On the residue level, the only 'covalent' bonds I can imagine are between the nodes neighboring in the sequence or the sulfur-bridges between two cysteines...  Most covalent bonds are within the aminoacids themselves which are reduced to a single node, so maybe 'covalent bond' feature doesn't belong in the residue level gnn?

**Comment by DaniBodor** [comment]
The position within the sequence is not currently part of any other feature, right? So there is no other determination of whether or not two residues are neighbors. If we remove the covalent feature we should replace it with a different feature that checks whether or not two residues are neighbors in the linear sequence.

Being neighbors would be a more reliable check than the current distance check, but would (as you mention) exclude cysteine bridges. Perhaps it would be more efficient and accurate to include cysteine bridging as a specific feature to cysteine residues somehow and sequence-neighbors as a generic residue feature. That would require restructuring a bit, which we might want to do at a later stage.

For a quick answer to Giulia's question right now: there is no reason I can imagine that the cutoff should be different for atom level graphs than for residue level graphs.

**Comment by gcroci2** [comment]
> The position within the sequence is not currently part of any other feature, right? So there is no other determination of whether or not two residues are neighbors (apart from distance, as is true for atom graphs). If we remove the covalent feature we should replace it with a different feature that checks whether or not two residues are neighbors in the linear sequence.
> 
> Being neighbors would be a more reliable check than the current distance check, but would (as you mention) exclude cysteine bridges. Perhaps it would be more efficient and accurate to include cysteine bridging as a specific feature to cysteine residues somehow and sequence-neighbors as a generic residue feature. That would require restructuring a bit, which we might want to do at a later stage. For now, the covalent feature can be used just as a determinant of whether or not residues are neighbors or partnered cysteines (and just the nomenclature is a bit awkward, but the network doesn't care about nomenclature).
> 

I agree, let's keep the covalent feature for now. 

> For a quick answer to Giulia's question right now: there is no reason I can imagine that the cutoff should be different for atom level graphs than for residue level graphs, because at the end of the day the cutoff distance is checked at the atom level for both graph types (for residue graphs it checks whether any atom within one residue is in proximity to any atom within the other).

You're right. I'll modify MAX_COVALENT_DISTANCE to 2.1 then, and I'll close the issue. It would be nice anyway to share the code you used for representing covalent bonds for atomic level, it may be handy also for other issues and could be a nice addition to the package @DTRademaker @KevinVG207
