### ISSUE TITLE
Add data augmentation option

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#278]
We should add the possibility to augment data in grid case. See [data_augmentation](https://github.com/DeepRank/deeprank/blob/4fc32407288e4c05bee2043ce192f408eed9539b/deeprank/generate/DataGenerator.py#L42) in the former `DataGenerator` of deeprank.

- Do we want to add such an option during the generation of the hdf5 files (query module), or at a later stage, when generating the `GridDataset`? (I would go for the latter)
- In the latter case, do we want to write such augmentations in the hdf5 files? I would avoid that.

**Comment by DaniBodor** [comment]
What types of augmentation are we thinking about?  


> Do we want to add such an option during the generation of the hdf5 files (query module), or at a later stage, when generating the `GridDataset`? (I would go for the latter)


I think during query is not a good idea, because normally only the training data should be augmented, and not the validation or test data. In query, we are not yet (and do not want to be) defining which data will be for training and which for validation/testing.

Also, for many types of (randomized) augmentations (e.g. random rotation), each epoch can use a different random rotation, so ideally the augmentations only happen at that point rather than in the `GridDataset` class.  
For predetermined augmentations (e.g. mirroring all data) this wouldn't be an issue, but probably better to do all augmentations in the same way.

**Comment by cbaakman** [comment]
In the original deeprank, data is augmented by rotating points in space by a random rotation around a random axis.
The points hold all the feature values.
After rotation, the points are mapped to the grid.

**Comment by cbaakman** [comment]
This was done in #336.
