### ISSUE TITLE
Verify that the grid orientation is the same as in deeprank for `ProteinProteinInterfaceResidueQuery `

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#320]
This has already been verified for `ProteinProteinInterfaceAtomicQuery`, see issue #281 and PR #312.

We should verify that the grid generated with deeprank-core has the same orientation of the one generated with deeprank for `ProteinProteinInterfaceResidueQuery` as well.

**Comment by cbaakman** [comment]
During the grid orientation test on the atomic grid, I noticed that there's no code for centering the grid. Something will have to be implemented for this..

**Comment by gcroci2** [comment]
> During the grid orientation test on the atomic grid, I noticed that there's no code for centering the grid. Something will have to be implemented for this..

I opened #321 for it

**Comment by cbaakman** [comment]
There's another issue with implementing this:
For centering the grid, the old deeprank selected contact atoms with a 8.5 A distance cutoff.
For selecting residues to take into the equation, the old deeprank selected residues with a 5.5 A distance cutoff.
The problem is that deeprank core can only use one cutoff, for building a grid.

My question @LilySnow : do we want to also implement this system with two cutoff values in deeprank core?

**Comment by cbaakman** [comment]
So after our meeting, we decided that the grid features do not necessarily need to have exactly the same coordinates. What does matter is that the deeprank-core produces similar results as in:
ttps://doi.org/10.1038/s41467-021-27396-0
